name: Build and test
on:
  # Build PRs 
  pull_request: ~
  # On push event
  push:
    # Build only changes pushed into the `master` branch.
    branches:
      - master
      - pipeline
    # Ignore documentation changes (Netlify will handle this)
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '**/*.md'

# Currently you cannot use ${{ env.IS_FORK }} for some reason, which is why you might need to copy-paste some of these.
env:
  REPOSITORY: ${{ github.repository }}
  IS_FORK: ${{ github.repository != 'carlspring/github-actions-experimentation' }}
  IS_PR: ${{ github.event_name == 'pull_request' }}
  EVENT_NAME: ${{ toJSON(github.event_name) }}
  # format: username:branch
  PR_HEAD_LABEL: ${{ toJSON(github.event.pull_request.head.label) }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  checkout-and-apply-changes:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Detect Changes From Upstream
        id: detect_changes_from_upstream
        uses: carlspring/detect-branch-changes-action@main
        with:
          base_branch: remotes/origin/master
          pathspec: "scripts"

      - name: Check if changes were detected
        if: steps.detect_changes_from_upstream.outputs.changed == 'true'
        run: echo "There were changes detected in the upstream branch!"

      - name: Fail if changes were detected
        if: steps.detect_changes_from_upstream.outputs.changed == 'true'
        run: exit 1
        
